### ISSUE TITLE
Data structure improvements

### ISSUE THREAD

**Issue by pmelab** [AmazeeLabs/ckeditor5_sections#62]
## Status quo
* Sections stores HTML data in simple rich text html fields. Historically the idea was to be able to use the HTML “as is”. Maybe we should rethink if this is worth it.
* A computed property provides access to the “raw” information when needed.
* The configuration which templates apply for a given field is stored in the editor settings.
* It is already possible to transform from HTML to  raw data and the other way around.

## Problems
* Template changes require a drastic upgrade through all existing content. Even if the stored data did not change.
* Typing is fuzzy, since typed data has no access to the format that is being used during editing and therefore doesn’t know about the used template. Right know its “guessing”.
* Each field requires its own input format to be able to enforce a document structure.
* Parsing raw data at runtime is rather costly with a big amount of templates.

## Solutions
1. Move template settings from the editor plugin to field instance. This solves 2 & 3.
2. Store parsed JSON instead of HTML and re-assemble to a full html document on demand (editing/preview). Solves 1 & 4.

## Steps to take
1. Provide a dedicated field type
	* Settings for template directory and root template
	* Stores JSON data
	* Computed property gives access to assembled document
	* Field widget transforms between html and data back & forth
		* still use editor plugins, but only “compatible” ones? Possibility: WYSIWYG (CKEditor) and JSON/YAML (CodeMirror or similar)
	* Enable output filters on JSON data or run them on separate properties later on?
		* tokens
		* link replacements
		* … ?		
2. Provide an upgrade path
	1. Create new field of the new type.
	2. Migrate data from old html field to new one
		1. Has to run for each revision of each affected entity type
		2. Solid batch process necessary
3. Provide a data update API for the remaining template changes that modify the underlying structure
          * New required properties
          * Field type changes
          * Renaming fields
          * ....

An idea how this update API could look like:
```php
<?php
function my_module_post_update_teaser_changes() {
  \Drupal::service('sections.update_manager')->update([
    'Teaser' => function($teaser) {
      // Renamed "title" field to "headline"
      $teaser['headline'] = $teaser['title'];
      unset($teaser['title']);
    }
  ]);
}
```

## Open questions to discuss
- [ ] Output filtering on JSON?
- [ ] Use editor plugins for new field type?

**Comment by pmelab** [comment]
On output filtering: A lot of filters would just work on JSON (e.g. token replacement), but everything that expects valid HTML will break. Technically we could just run JSON -> HTML, apply output filters and then extract data again. But this would mean we lose the performance benefit of already storing parsed data.
Another option could be tagging output filters as compatible and only allow these.

**Comment by dan2k3k4** [comment]
We should also keep in mind how translations would work, sending a translation job via `TMGMT` - would we send the JSON to be translated or the computed HTML?

I suppose the `diff` module would use the computed HTML.

**Comment by pmelab** [comment]
I think TMGMT is save. When using it "on site" it would just invoke the configured field widget, and for translation services we need special treatment anyway, like we have it on daimler now.

**Comment by pmelab** [comment]
Another thought on output filtering: I think the "cleanest" way would be to do the filtering on-demand per property in GraphQL or Twig, since this would be conceptually the same as what paragraphs would do with output filtered fields. But I'm not sure if this would be feasible or not.
